### ISSUE TITLE
知乎文章说的bug修复了吗？

### ISSUE THREAD

**Issue by zwl1619** [huangbinjie/blog#2]
[知乎文章](https://zhuanlan.zhihu.com/p/32075662)说：

![image](https://user-images.githubusercontent.com/13177997/50450310-15e3a500-0968-11e9-822f-01b16c0cf5ba.png)

那么，目前的版本此bug修复了吗？

**Comment by huangbinjie** [comment]
修了，如果还有 bug 记得回来艾特我。先关了
